"""
CartoGraph — global variable registry

Every [VARIABLE] placeholder from uk-ecom-intel-brief (1).md is defined here.
Values are loaded from environment variables where sensible; otherwise they are
compile-time constants that never change (enum-style lists).

Usage:
    from app.config.variables import VARIABLES, cg_settings

    country = VARIABLES["COUNTRY"]                  # "UK"
    tier    = cg_settings.DEFAULT_SUBSCRIPTION_TIER # from .env
"""

from __future__ import annotations

import os
from typing import Any

# ---------------------------------------------------------------------------
# Compile-time constants — enum-style lists that define the product surface
# ---------------------------------------------------------------------------

VARIABLES: dict[str, Any] = {
    # Default market
    "COUNTRY": os.getenv("CARTOGRAPH_COUNTRY", "UK"),
    # Future market
    "EXPANSION_COUNTRY": os.getenv("CARTOGRAPH_EXPANSION_COUNTRY", "USA"),
    # Generated by Agent 1 at runtime; starts empty
    "KEYWORD_SET": [],
    # Commercial intent classifications tracked across all agents
    "INTENT_TYPE": [
        "transactional",
        "commercial_investigation",
        "price_sensitive",
        "delivery_focused",
        "geo_qualified",
    ],
    # SERP features detected and tracked by Agents 2 and 6
    "SERP_FEATURE": [
        "shopping_carousel",
        "people_also_ask",
        "featured_snippet",
        "local_pack",
        "sitelinks",
        "image_pack",
        "ai_overview",
    ],
    # Pluggable data provider IDs — used as discriminators in the provider interface
    "DATA_SOURCE": [
        "dataforseo_serp",
        "dataforseo_backlinks",
        "moz_api",
        "wappalyzer_self_hosted",
        "direct_scrape",
        "companies_house_api",
        "search_console_import",
        "internal_calculation",
    ],
    # Cron cadences used in agent scheduling
    "UPDATE_FREQUENCY": [
        "daily",
        "weekly",
        "bi_weekly",
        "monthly",
        "quarterly",
    ],
    # Subscription tiers — matches Stripe product IDs in settings
    "SUBSCRIPTION_TIER": [
        "free",
        "starter",
        "professional",
        "business",
        "enterprise",
    ],
    # Target customer personas
    "USER_PERSONA": [
        "agency",
        "saas_vendor",
        "affiliate_seo",
        "link_builder",
        "pe_investor",
        "dtc_brand",
        "aggregator",
        "analyst",
    ],
}

# ---------------------------------------------------------------------------
# Intent modifier sets — used by Agent 1 (Keyword Miner)
# ---------------------------------------------------------------------------

UK_INTENT_MODIFIERS: dict[str, list[str]] = {
    "transactional": ["buy", "order", "shop", "purchase"],
    "commercial_investigation": ["best", "top", "review", "compare", "vs"],
    "price_sensitive": [
        "cheap",
        "affordable",
        "discount",
        "sale",
        "voucher",
        "discount code",
    ],
    "delivery_focused": [
        "free delivery",
        "next day delivery",
        "click and collect",
    ],
    "geo_qualified": ["{product} UK", "{product} online UK"],
}

# ---------------------------------------------------------------------------
# SERP feature weights — used by Agent 6 (Intent Scoring)
# ---------------------------------------------------------------------------

SERP_FEATURE_WEIGHTS: dict[str, float] = {
    "shopping_carousel": 3.0,
    "ai_overview": 2.0,
    "featured_snippet": 2.0,
    "sitelinks": 1.5,
    "people_also_ask": 1.0,
    "local_pack": 1.0,
    "image_pack": 0.5,
}

# ---------------------------------------------------------------------------
# GDPR-safe email prefixes — only these are stored, never personal inboxes
# ---------------------------------------------------------------------------

GDPR_SAFE_EMAIL_PREFIXES: frozenset[str] = frozenset(
    {"info", "hello", "sales", "support", "contact", "enquiries", "team", "shop"}
)

# ---------------------------------------------------------------------------
# Env-backed runtime settings (thin wrapper — avoids duplicating BaseSettings)
# ---------------------------------------------------------------------------


class CartoGraphSettings:
    """Runtime config for CartoGraph-specific env vars not in core Settings."""

    # DataForSEO credentials
    DATAFORSEO_LOGIN: str = os.getenv("DATAFORSEO_LOGIN", "")
    DATAFORSEO_PASSWORD: str = os.getenv("DATAFORSEO_PASSWORD", "")
    DATAFORSEO_BASE_URL: str = os.getenv(
        "DATAFORSEO_BASE_URL", "https://api.dataforseo.com"
    )

    # Redis / Celery
    REDIS_URL: str = os.getenv("REDIS_URL", "redis://redis:6379/0")
    CELERY_BROKER_URL: str = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")
    CELERY_RESULT_BACKEND: str = os.getenv(
        "CELERY_RESULT_BACKEND", "redis://redis:6379/1"
    )

    # Moz API
    MOZ_ACCESS_ID: str = os.getenv("MOZ_ACCESS_ID", "")
    MOZ_SECRET_KEY: str = os.getenv("MOZ_SECRET_KEY", "")

    # Companies House API
    COMPANIES_HOUSE_API_KEY: str = os.getenv("COMPANIES_HOUSE_API_KEY", "")

    # Agent scheduling
    KEYWORD_MINER_BATCH_SIZE: int = int(
        os.getenv("KEYWORD_MINER_BATCH_SIZE", "200")
    )
    SERP_DISCOVERY_BATCH_SIZE: int = int(
        os.getenv("SERP_DISCOVERY_BATCH_SIZE", "500")
    )
    SERP_DISCOVERY_GEO: str = os.getenv("SERP_DISCOVERY_GEO", "2826")  # UK location code
    SERP_DISCOVERY_LANGUAGE: str = os.getenv("SERP_DISCOVERY_LANGUAGE", "en")

    # Data schema
    SCHEMA_VERSION: str = "1.0.0"
    DEFAULT_COUNTRY: str = os.getenv("CARTOGRAPH_COUNTRY", "UK")


cg_settings = CartoGraphSettings()
